### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by IgorGanapolsky** [WeMakeBetterApps/MortarLib#1]
Hello,
I cannot compile your project.  I get an error:

> Error:(41, 0) No such property: ossrhUsername for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

**Comment by ScottPierce** [comment]
if you look in the build.gradle it's looking for a ossrhUsername, and probably the password defined as variables. It's used for signing and uploading to maven central. You can either set dummy values for those variables in your gradle.properties file or just remove those parts from the build.gradle files.

**Comment by IgorGanapolsky** [comment]
Thank you.
